// @generated by qualification/ssrc_true_peak_terminal/promote_ssrc_true_peak_terminal.py
//
// Intentionally empty in the source delivery.  The certified SSRC terminal is
// fail-closed until an operator executes qualification on the exact runtime
// machine/build and promotes the resulting report.  Never hand-author records.

use super::CommissionedSsrcTruePeakTerminalRecord;

pub(crate) const COMMISSIONED_SSRC_TRUE_PEAK_TERMINALS:
    &[CommissionedSsrcTruePeakTerminalRecord] = &[];
