//! Cue file generation implementation

use super::{ConversionConfig, ConversionResult, FeatureError, FeatureResult};
use std::path::{Path, PathBuf};
use std::time::Duration;
use tokio::fs;

/// Album metadata for cue file generation
#[derive(Debug, Clone)]
pub struct AlbumMetadata {
    pub title: String,
    pub artist: String,
    pub genre: Option<String>,
    pub year: Option<String>,
    pub tracks: Vec<TrackMetadata>,
}

#[derive(Debug, Clone)]
pub struct TrackMetadata {
    pub number: u32,
    pub title: String,
    pub artist: String,
    pub filename: String,
    pub format: AudioFormat,
    pub duration: Option<Duration>,
    pub replaygain_track_gain: Option<String>,
    pub replaygain_track_peak: Option<String>,
    pub replaygain_album_gain: Option<String>,
    pub replaygain_album_peak: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum AudioFormat {
    Flac,
    Mp3,
    Opus,
    Aac,
    Wav,
    Aiff,
    WavPack,
}

impl AudioFormat {
    pub fn from_extension(ext: &str) -> Option<Self> {
        match ext.to_lowercase().as_str() {
            "flac" => Some(AudioFormat::Flac),
            "mp3" => Some(AudioFormat::Mp3),
            "opus" => Some(AudioFormat::Opus),
            "m4a" | "aac" => Some(AudioFormat::Aac),
            "wav" => Some(AudioFormat::Wav),
            "aiff" | "aif" => Some(AudioFormat::Aiff),
            "wv" => Some(AudioFormat::WavPack),
            _ => None,
        }
    }

    pub fn cue_format(&self) -> &'static str {
        match self {
            AudioFormat::Flac => "FLAC",
            AudioFormat::Mp3 => "MP3",
            AudioFormat::Opus => "OPUS",
            AudioFormat::Aac => "AAC",
            AudioFormat::Wav => "WAVE",
            AudioFormat::Aiff => "AIFF",
            AudioFormat::WavPack => "WAVPACK",
        }
    }
}

/// Custom error type for cue file operations
#[derive(Debug, thiserror::Error)]
pub enum CueFileError {
    #[error("No audio files found for cue generation")]
    NoAudioFiles,

    #[error("Metadata extraction failed: {0}")]
    MetadataExtraction(String),

    #[error("Invalid album structure: {0}")]
    InvalidAlbum(String),

    #[error("File I/O error: {0}")]
    Io(#[from] std::io::Error),
}

/// Generate cue file for album conversion
pub async fn generate_cue_file(
    output_dir: &Path,
    audio_files: &[PathBuf],
    _config: &ConversionConfig,
    conversion_results: &[ConversionResult],
) -> FeatureResult<PathBuf> {
    // Extract album metadata from files and directory
    let album_metadata =
        extract_album_metadata(output_dir, audio_files, conversion_results).await?;

    // Generate cue file content
    let cue_content = generate_cue_content(&album_metadata);

    // Determine cue filename
    let cue_filename = sanitize_filename(&format!("{}.cue", album_metadata.title));
    let cue_path = output_dir.join(&cue_filename);

    // Write cue file
    fs::write(&cue_path, cue_content)
        .await
        .map_err(|e| FeatureError::Permission(format!("Cannot write cue file: {}", e)))?;

    log::info!("Cue file generated: {}", cue_path.display());

    Ok(cue_path)
}

/// Generate cue file for merged album (single FILE with multiple TRACKs)
pub async fn generate_merged_cue_file(
    output_dir: &Path,
    merged_filename: &str,
    album_artist: &str,
    album_title: &str,
    album_year: Option<&str>,
    track_titles: &[String],
    track_durations: &[std::time::Duration],
) -> FeatureResult<PathBuf> {
    use tokio::fs;

    if track_titles.len() != track_durations.len() {
        return Err(FeatureError::Format(
            "Track titles and durations length mismatch".to_string(),
        ));
    }

    if track_titles.is_empty() {
        return Err(FeatureError::Format(
            "No tracks provided for cue generation".to_string(),
        ));
    }

    let mut cue = String::new();

    // Header
    if let Some(year) = album_year {
        cue.push_str(&format!("REM DATE \"{}\"\n", escape_cue_string(year)));
    }
    cue.push_str("REM COMMENT \"Generated by tonepoet\"\n");
    cue.push_str(&format!(
        "PERFORMER \"{}\"\n",
        escape_cue_string(album_artist)
    ));
    cue.push_str(&format!("TITLE \"{}\"\n", escape_cue_string(album_title)));

    // Determine format from extension
    let extension = merged_filename.rsplit('.').next().unwrap_or("flac");
    let file_format = AudioFormat::from_extension(extension)
        .map(|fmt| fmt.cue_format())
        .unwrap_or("WAVE");

    cue.push_str(&format!(
        "FILE \"{}\" {}\n",
        escape_cue_string(merged_filename),
        file_format
    ));

    // Tracks with cumulative timestamps
    let mut cumulative_duration = std::time::Duration::ZERO;
    for (index, (title, duration)) in track_titles.iter().zip(track_durations.iter()).enumerate() {
        let track_number = (index + 1) as u32;

        cue.push_str(&format!("  TRACK {:02} AUDIO\n", track_number));
        cue.push_str(&format!("    TITLE \"{}\"\n", escape_cue_string(title)));
        cue.push_str(&format!(
            "    PERFORMER \"{}\"\n",
            escape_cue_string(album_artist)
        ));
        cue.push_str(&format!(
            "    INDEX 01 {}\n",
            format_cue_timestamp(&cumulative_duration)
        ));

        cumulative_duration += *duration;
    }

    // Write cue file
    let cue_filename = sanitize_filename(&format!("{}.cue", album_title));
    let cue_path = output_dir.join(&cue_filename);

    fs::write(&cue_path, cue)
        .await
        .map_err(|e| FeatureError::Permission(format!("Cannot write cue file: {}", e)))?;

    log::info!("Merged cue file generated: {}", cue_path.display());

    Ok(cue_path)
}

/// Format duration as cue timestamp (MM:SS:FF where FF is frames, 75 fps)
fn format_cue_timestamp(duration: &std::time::Duration) -> String {
    let total_seconds = duration.as_secs();
    let minutes = total_seconds / 60;
    let seconds = total_seconds % 60;
    let frames = (duration.subsec_millis() * 75) / 1000;
    format!("{:02}:{:02}:{:02}", minutes, seconds, frames)
}

/// Extract album and track metadata for cue generation
async fn extract_album_metadata(
    output_dir: &Path,
    audio_files: &[PathBuf],
    conversion_results: &[ConversionResult],
) -> FeatureResult<AlbumMetadata> {
    if audio_files.is_empty() {
        return Err(FeatureError::Format(
            "No audio files provided for cue generation".to_string(),
        ));
    }

    // Extract album info from directory name
    let (album_artist, album_title, album_year) = parse_album_from_directory_name(output_dir);

    // Build map of output filename -> ReplayGain values
    let mut rg_map = std::collections::HashMap::new();
    for result in conversion_results {
        if let Some(filename) = result.output_file.file_name() {
            if let Some(rg) = &result.replaygain_values {
                rg_map.insert(filename.to_string_lossy().to_string(), rg.clone());
            }
        }
    }

    // Extract track metadata from each file
    let mut tracks = Vec::new();
    for (index, file_path) in audio_files.iter().enumerate() {
        let track_number = (index + 1) as u32;

        // Extract track metadata (filename parsing as fallback)
        let mut track_metadata = extract_track_metadata(file_path, track_number)
            .await
            .unwrap_or_else(|_| fallback_track_metadata(file_path, track_number, &album_artist));

        // Add ReplayGain data if available
        if let Some(filename) = file_path.file_name() {
            if let Some(rg) = rg_map.get(&filename.to_string_lossy().to_string()) {
                track_metadata.replaygain_track_gain = rg.track_gain.clone();
                track_metadata.replaygain_track_peak = rg.track_peak.clone();
                track_metadata.replaygain_album_gain = rg.album_gain.clone();
                track_metadata.replaygain_album_peak = rg.album_peak.clone();
            }
        }

        tracks.push(track_metadata);
    }

    // Sort tracks by track number
    tracks.sort_by_key(|t| t.number);

    Ok(AlbumMetadata {
        title: album_title,
        artist: album_artist,
        genre: None, // TODO: Extract from first file metadata
        year: album_year,
        tracks,
    })
}

/// Generate cue file content from metadata
fn generate_cue_content(album: &AlbumMetadata) -> String {
    let mut cue = String::new();

    // Header with album metadata
    if let Some(genre) = &album.genre {
        cue.push_str(&format!("REM GENRE \"{}\"\n", escape_cue_string(genre)));
    }
    if let Some(year) = &album.year {
        cue.push_str(&format!("REM DATE \"{}\"\n", escape_cue_string(year)));
    }
    cue.push_str("REM COMMENT \"Generated by tonepoet\"\n");

    // Album-level ReplayGain tags (use first track's album gain values)
    // Note: Due to per-file processing, each track may have different album gain values
    // We use the first track's values as canonical for the album
    if let Some(first_track) = album.tracks.first() {
        if let Some(ref album_gain) = first_track.replaygain_album_gain {
            cue.push_str(&format!("REM REPLAYGAIN_ALBUM_GAIN {}\n", album_gain));
        }
        if let Some(ref album_peak) = first_track.replaygain_album_peak {
            cue.push_str(&format!("REM REPLAYGAIN_ALBUM_PEAK {}\n", album_peak));
        }
    }

    cue.push_str(&format!(
        "PERFORMER \"{}\"\n",
        escape_cue_string(&album.artist)
    ));
    cue.push_str(&format!("TITLE \"{}\"\n", escape_cue_string(&album.title)));

    // Track entries
    for track in &album.tracks {
        cue.push_str(&format!(
            "FILE \"{}\" {}\n",
            escape_cue_string(&track.filename),
            track.format.cue_format()
        ));
        cue.push_str(&format!("  TRACK {:02} AUDIO\n", track.number));
        cue.push_str(&format!(
            "    TITLE \"{}\"\n",
            escape_cue_string(&track.title)
        ));
        cue.push_str(&format!(
            "    PERFORMER \"{}\"\n",
            escape_cue_string(&track.artist)
        ));

        // Track-level ReplayGain tags
        if let Some(ref track_gain) = track.replaygain_track_gain {
            cue.push_str(&format!("    REM REPLAYGAIN_TRACK_GAIN {}\n", track_gain));
        }
        if let Some(ref track_peak) = track.replaygain_track_peak {
            cue.push_str(&format!("    REM REPLAYGAIN_TRACK_PEAK {}\n", track_peak));
        }

        cue.push_str("    INDEX 01 00:00:00\n");
    }

    cue
}

// Implementation helper functions (TODO: Implement these)

async fn extract_track_metadata(
    _file_path: &PathBuf,
    _track_number: u32,
) -> Result<TrackMetadata, CueFileError> {
    // Metadata extraction would require additional dependencies:
    // - FLAC: metaflac or existing hexload-tui metadata functions
    // - MP3: id3 crate
    // - Opus: opus_headers crate
    // - AAC: mp4ameta crate
    // For now, return error to use fallback metadata from filename

    Err(CueFileError::MetadataExtraction(
        "Using filename fallback".to_string(),
    ))
}

fn parse_album_from_directory_name(output_dir: &Path) -> (String, String, Option<String>) {
    // Parse directory name: "Artist - Album (Year) [Format] {Pressing} [Uploader]"
    let dir_name = output_dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("Unknown Album");

    // TODO: Implement robust parsing
    // For now, basic fallback
    if let Some(dash_pos) = dir_name.find(" - ") {
        let artist = dir_name[..dash_pos].to_string();
        let rest = &dir_name[dash_pos + 3..];

        // Extract album title (before year parentheses)
        let album = if let Some(paren_pos) = rest.find(" (") {
            rest[..paren_pos].to_string()
        } else {
            rest.to_string()
        };

        // Extract year if present
        let year = if let Some(year_start) = rest.find(" (") {
            if let Some(year_end) = rest[year_start..].find(")") {
                let year_part = &rest[year_start + 2..year_start + year_end];
                Some(year_part.to_string())
            } else {
                None
            }
        } else {
            None
        };

        (artist, album, year)
    } else {
        ("Unknown Artist".to_string(), dir_name.to_string(), None)
    }
}

fn fallback_track_metadata(
    file_path: &PathBuf,
    track_number: u32,
    album_artist: &str,
) -> TrackMetadata {
    // Parse filename: "01 - Track Name.ext"
    let filename = file_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("Unknown Track");

    let format = AudioFormat::from_extension(
        file_path
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("flac"),
    )
    .unwrap_or(AudioFormat::Flac);

    // Parse track title from filename
    let title = if let Some(dash_pos) = filename.find(" - ") {
        let title_part = &filename[dash_pos + 3..];
        // Remove extension
        if let Some(dot_pos) = title_part.rfind('.') {
            title_part[..dot_pos].to_string()
        } else {
            title_part.to_string()
        }
    } else {
        format!("Track {:02}", track_number)
    };

    TrackMetadata {
        number: track_number,
        title,
        artist: album_artist.to_string(),
        filename: filename.to_string(),
        format,
        duration: None, // TODO: Extract from file
        replaygain_track_gain: None,
        replaygain_track_peak: None,
        replaygain_album_gain: None,
        replaygain_album_peak: None,
    }
}

fn escape_cue_string(s: &str) -> String {
    // Escape quotes and backslashes for cue file format
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn sanitize_filename(filename: &str) -> String {
    // Remove/replace invalid filename characters
    filename
        .chars()
        .map(|c| match c {
            '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|' => '_',
            _ => c,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_audio_format_detection() {
        assert_eq!(AudioFormat::from_extension("flac"), Some(AudioFormat::Flac));
        assert_eq!(AudioFormat::from_extension("OPUS"), Some(AudioFormat::Opus));
        assert_eq!(AudioFormat::from_extension("mp3"), Some(AudioFormat::Mp3));
    }

    #[test]
    fn test_cue_format_strings() {
        assert_eq!(AudioFormat::Opus.cue_format(), "OPUS");
        assert_eq!(AudioFormat::Mp3.cue_format(), "MP3");
        assert_eq!(AudioFormat::Flac.cue_format(), "FLAC");
    }

    #[test]
    fn test_filename_sanitization() {
        assert_eq!(sanitize_filename("Album: The Movie"), "Album_ The Movie");
        assert_eq!(sanitize_filename("Track \"Name\""), "Track _Name_");
    }

    #[test]
    fn test_cue_string_escaping() {
        assert_eq!(escape_cue_string("Song \"Title\""), "Song \\\"Title\\\"");
        assert_eq!(escape_cue_string("Path\\File"), "Path\\\\File");
    }

    #[test]
    fn test_directory_name_parsing() {
        let (artist, album, year) = parse_album_from_directory_name(Path::new(
            "Artist - Album Title (1995) [FLAC] {Pressing} [Uploader]",
        ));
        assert_eq!(artist, "Artist");
        assert_eq!(album, "Album Title");
        assert_eq!(year, Some("1995".to_string()));
    }
}
