//! Standalone CUE sheet generation from tagged audio files in the browse view.
//! Separate from the conversion pipeline's generator in tonepoet-features.

use std::path::Path;
use std::time::Duration;

/// Album-level metadata for CUE header.
pub struct CueAlbumInfo {
    pub title: String,
    pub artist: String,
    pub year: Option<String>,
    pub genre: Option<String>,
}

/// Per-track metadata for a CUE entry.
pub struct CueTrackInfo {
    pub filename: String,
    pub title: String,
    pub artist: String,
    pub track_number: u32,
    pub duration: Duration,
    pub format_tag: String,
}

/// Generate a multi-file CUE sheet (one FILE per track, INDEX 01 00:00:00).
pub fn generate_multifile_cue(album: &CueAlbumInfo, tracks: &[CueTrackInfo]) -> String {
    let mut cue = String::new();
    write_header(&mut cue, album);

    for t in tracks {
        cue.push_str(&format!(
            "FILE \"{}\" {}\n",
            escape(&t.filename),
            t.format_tag,
        ));
        cue.push_str(&format!("  TRACK {:02} AUDIO\n", t.track_number));
        cue.push_str(&format!("    TITLE \"{}\"\n", escape(&t.title)));
        cue.push_str(&format!("    PERFORMER \"{}\"\n", escape(&t.artist)));
        cue.push_str("    INDEX 01 00:00:00\n");
    }

    cue
}

/// Generate a single-image CUE sheet (one FILE, cumulative timestamps).
pub fn generate_single_image_cue(
    album: &CueAlbumInfo,
    tracks: &[CueTrackInfo],
    image_filename: &str,
    image_format_tag: &str,
) -> String {
    let mut cue = String::new();
    write_header(&mut cue, album);

    cue.push_str(&format!(
        "FILE \"{}\" {}\n",
        escape(image_filename),
        image_format_tag,
    ));

    let mut cumulative = Duration::ZERO;
    for t in tracks {
        cue.push_str(&format!("  TRACK {:02} AUDIO\n", t.track_number));
        cue.push_str(&format!("    TITLE \"{}\"\n", escape(&t.title)));
        cue.push_str(&format!("    PERFORMER \"{}\"\n", escape(&t.artist)));
        cue.push_str(&format!("    INDEX 01 {}\n", format_timestamp(&cumulative)));
        cumulative += t.duration;
    }

    cue
}

/// Map a file extension to the CUE FILE type keyword.
pub fn cue_format_tag(ext: &str) -> &'static str {
    match ext.to_ascii_lowercase().as_str() {
        "flac" => "FLAC",
        "mp3" => "MP3",
        "opus" => "OPUS",
        "m4a" | "aac" => "AAC",
        "wav" => "WAVE",
        "aiff" | "aif" => "AIFF",
        "wv" => "WAVPACK",
        _ => "WAVE",
    }
}

/// Derive a sanitised CUE filename from album metadata.
pub fn cue_output_filename(album: &CueAlbumInfo) -> String {
    let base = if album.artist.is_empty()
        || album.artist == "Unknown Artist"
        || album.artist == "Various Artists"
    {
        album.title.clone()
    } else {
        format!("{} - {}", album.artist, album.title)
    };
    let sanitised: String = base
        .chars()
        .map(|c| match c {
            '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|' => '_',
            _ => c,
        })
        .collect();
    format!("{}.cue", sanitised)
}

// ── internal helpers ────────────────────────────────────────────────

fn write_header(cue: &mut String, album: &CueAlbumInfo) {
    if let Some(genre) = &album.genre {
        cue.push_str(&format!("REM GENRE \"{}\"\n", escape(genre)));
    }
    if let Some(year) = &album.year {
        cue.push_str(&format!("REM DATE \"{}\"\n", escape(year)));
    }
    cue.push_str("REM COMMENT \"Generated by tonepoet\"\n");
    cue.push_str(&format!("PERFORMER \"{}\"\n", escape(&album.artist)));
    cue.push_str(&format!("TITLE \"{}\"\n", escape(&album.title)));
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn format_timestamp(d: &Duration) -> String {
    let total_secs = d.as_secs();
    let minutes = total_secs / 60;
    let seconds = total_secs % 60;
    let frames = (d.subsec_millis() * 75) / 1000;
    format!("{:02}:{:02}:{:02}", minutes, seconds, frames)
}

/// Build album + track info by probing files and reading tags.
/// Falls back to filename parsing when tags are missing.
/// `cue_dir` is the directory where the CUE file will be written;
/// FILE references are made relative to it.
pub fn gather_cue_info(
    paths: &[std::path::PathBuf],
    cue_dir: &Path,
) -> Result<(CueAlbumInfo, Vec<CueTrackInfo>), String> {
    if paths.is_empty() {
        return Err("No audio files".into());
    }

    let mut tracks = Vec::with_capacity(paths.len());

    // Read metadata + duration for each file.
    let mut album_title: Option<String> = None;
    let mut album_artist: Option<String> = None;
    let mut album_year: Option<String> = None;
    let mut album_genre: Option<String> = None;

    for path in paths {
        let meta = super::probe::read_metadata(path).ok();
        let info = super::probe::probe_audio(path).ok();

        let duration = info
            .as_ref()
            .map(|i| Duration::from_secs_f64(i.duration_secs))
            .unwrap_or(Duration::ZERO);

        let ext = path
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("wav");
        let format_tag = cue_format_tag(ext).to_string();

        // FILE reference: relative to CUE output directory.
        let filename = path
            .strip_prefix(cue_dir)
            .unwrap_or(path)
            .to_string_lossy()
            .to_string();

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("");

        // Track number: prefer tag, fall back to filename.
        let track_number = meta
            .as_ref()
            .and_then(|m| m.track_number)
            .unwrap_or_else(|| super::probe::extract_track_from_filename(stem));

        // Title: prefer tag, fall back to filename parsing.
        let title = meta
            .as_ref()
            .and_then(|m| m.title.clone())
            .unwrap_or_else(|| {
                let (_, parsed) = super::probe::parse_title_from_filename(stem);
                parsed.unwrap_or_else(|| stem.to_string())
            });

        // Artist: prefer tag.
        let artist = meta
            .as_ref()
            .and_then(|m| m.artist.clone())
            .unwrap_or_default();

        // Collect album-level info from first file that has it.
        if album_title.is_none() {
            album_title = meta.as_ref().and_then(|m| m.album.clone());
        }
        if album_artist.is_none() {
            album_artist = meta.as_ref().and_then(|m| m.artist.clone());
        }
        if album_year.is_none() {
            album_year = meta.as_ref().and_then(|m| m.year.clone());
        }
        if album_genre.is_none() {
            album_genre = meta.as_ref().and_then(|m| m.genre.clone());
        }

        tracks.push(CueTrackInfo {
            filename,
            title,
            artist,
            track_number,
            duration,
            format_tag,
        });
    }

    // Fall back to CUE output directory name for album info.
    let dir_name = cue_dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("Unknown Album");

    let album = CueAlbumInfo {
        title: album_title.unwrap_or_else(|| dir_name.to_string()),
        artist: album_artist.unwrap_or_else(|| "Unknown Artist".to_string()),
        year: album_year,
        genre: album_genre,
    };

    Ok((album, tracks))
}

/// Derive the hypothetical single-image filename from album metadata and
/// the extension of the first source file.
pub fn derive_image_filename(album: &CueAlbumInfo, first_path: &Path) -> String {
    let ext = first_path
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("flac");
    let base = if album.artist.is_empty()
        || album.artist == "Unknown Artist"
        || album.artist == "Various Artists"
    {
        album.title.clone()
    } else {
        format!("{} - {}", album.artist, album.title)
    };
    let sanitised: String = base
        .chars()
        .map(|c| match c {
            '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|' => '_',
            _ => c,
        })
        .collect();
    format!("{}.{}", sanitised, ext)
}
