use ratatui::style::{Color, Modifier, Style};

/// Style palette for embedding the picker in different applications.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FilePickerTheme {
    pub border: Style,
    pub border_dim: Style,
    pub title: Style,
    pub toolbar: Style,
    pub toolbar_active: Style,
    pub button: Style,
    pub button_focused: Style,
    pub button_disabled: Style,
    pub label: Style,
    pub text: Style,
    pub text_dim: Style,
    pub folder: Style,
    pub current_file: Style,
    pub selected: Style,
    pub progress_dialog: Style,
    pub progress_border: Style,
    pub progress_title: Style,
    pub progress_label: Style,
    pub progress_text: Style,
    pub progress_text_dim: Style,
    pub progress_current_file: Style,
    pub progress_button: Style,
    pub progress_button_focused: Style,
    pub progress_destructive: Style,
    pub header: Style,
    pub status: Style,
    pub menu: Style,
    pub menu_selected: Style,
    pub menu_disabled: Style,
    pub accelerator: Style,
    pub destructive: Style,
    pub progress_filled: Style,
    pub progress_unfilled: Style,
    pub progress_percent: Style,
    pub error: Style,
}

impl Default for FilePickerTheme {
    fn default() -> Self {
        Self {
            border: Style::default().fg(Color::Cyan),
            border_dim: Style::default().fg(Color::DarkGray),
            title: Style::default().fg(Color::White).add_modifier(Modifier::BOLD),
            toolbar: Style::default().fg(Color::White),
            toolbar_active: Style::default().fg(Color::Black).bg(Color::Cyan).add_modifier(Modifier::BOLD),
            button: Style::default().fg(Color::Black).bg(Color::Cyan),
            button_focused: Style::default().fg(Color::Black).bg(Color::White).add_modifier(Modifier::BOLD),
            button_disabled: Style::default().fg(Color::DarkGray).bg(Color::Black),
            label: Style::default().fg(Color::DarkGray),
            text: Style::default().fg(Color::White),
            text_dim: Style::default().fg(Color::Gray),
            folder: Style::default().fg(Color::Yellow),
            current_file: Style::default().fg(Color::Cyan),
            selected: Style::default().fg(Color::Black).bg(Color::Cyan).add_modifier(Modifier::BOLD),
            progress_dialog: Style::default(),
            progress_border: Style::default().fg(Color::Cyan),
            progress_title: Style::default().fg(Color::White).add_modifier(Modifier::BOLD),
            progress_label: Style::default().fg(Color::DarkGray),
            progress_text: Style::default().fg(Color::White),
            progress_text_dim: Style::default().fg(Color::Gray),
            progress_current_file: Style::default().fg(Color::Cyan),
            progress_button: Style::default().fg(Color::Black).bg(Color::Cyan),
            progress_button_focused: Style::default().fg(Color::Black).bg(Color::White).add_modifier(Modifier::BOLD),
            progress_destructive: Style::default().fg(Color::Black).bg(Color::Red).add_modifier(Modifier::BOLD),
            header: Style::default().fg(Color::Gray).add_modifier(Modifier::BOLD),
            status: Style::default().fg(Color::Black).bg(Color::Gray),
            menu: Style::default().fg(Color::Black).bg(Color::Gray),
            menu_selected: Style::default().fg(Color::Black).bg(Color::Cyan).add_modifier(Modifier::BOLD),
            menu_disabled: Style::default().fg(Color::DarkGray).bg(Color::Gray),
            accelerator: Style::default().fg(Color::Yellow).add_modifier(Modifier::UNDERLINED),
            destructive: Style::default().fg(Color::Black).bg(Color::Red).add_modifier(Modifier::BOLD),
            progress_filled: Style::default().fg(Color::Cyan),
            progress_unfilled: Style::default().fg(Color::DarkGray),
            progress_percent: Style::default().fg(Color::White),
            error: Style::default().fg(Color::Red),
        }
    }
}
